info:
  application:
    name: supplement-list
    description: list of supplements
    profile: generic

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: supplement-list
    description: list of supplements
    profile: generic
  profiles:
    active: dev